server:
  port: 8081
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/emsdb
    username: root
    hikari:
      maxLifetime: 20000
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
